services:
  postgres:
    image: postgres:15
    container_name: t3-chat-database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: t3chat
    ports:
      - '5432:5432'
    volumes:
      - t3_chat_database:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: t3-chat-cache
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - t3_chat_cache:/data

volumes:
  t3_chat_database:
  t3_chat_cache:
